version: '2'
services:
  news_tweets:
    image: docker-ina.rech.ina.fr/bmazoyer/igraph:latest
    container_name: news_tweets
    volumes:
        - /rex/local/bmtweet/news_twitter/:/usr/src/app
    stdin_open: true
    tty: true
    command: python /usr/src/app/main_all_data.py